# Pearl Lolo AI Agent Configuration

app:
  name: "Pearl Lolo AI Agent"
  version: "1.0.0"
  language: "both"  # english, arabic, both

ui:
  theme: "glassmorphism"
  primary_color: "#d2cdbd"
  secondary_color: "#95b3f4" 
  font_primary: "Inter"
  font_code: "Source Code Pro"
  language: "both"

ai:
  default_model: "local"
  models:
    local:
      provider: "ollama"
      model: "llama2"
      base_url: "http://localhost:11434"
    openai:
      api_key: ""
      model: "gpt-4"
    anthropic:
      api_key: ""
      model: "claude-2"
    hrm:
      enabled: false
      base_url: "http://localhost:8008"
      default_task: "sudoku"
      timeout: 30
      health_endpoint: "/health"
      check_health_on_startup: true

rag:
  enabled: true
  embedding_model: "all-MiniLM-L6-v2"
  vector_store: "chromadb"
  chunk_size: 1000
  chunk_overlap: 200

search:
  enabled: true
  provider: "google"
  api_key: ""
  search_engine_id: ""

personality:
  default: "lolo"
  profiles:
    lolo:
      name: "Lolo"
      language: "both"
      tone: "friendly"
      response_style: "detailed"
    professional:
      name: "Professional"
      language: "english" 
      tone: "formal"
      response_style: "concise"

system:
  auto_update: true
  log_level: "INFO"
  max_memory: "8GB"